# Generated by Django 6.0.2 on 2026-02-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Cash', 'Cash'), ('Bank', 'Bank Transfer')], default='M-Pesa', max_length=50),
        ),
    ]
